### PR TITLE
Fix webpack builds

### PR DESCRIPTION
**Pull request by remcohaszing**

### CODE REVIEW

**Comment by Lehren** [comment]
The built HTML pages do not have correct image references. 

For example `src=/01353140e1128935f4fce28cdbd29fe8.png`

should be `src=../01353140e1128935f4fce28cdbd29fe8.png`

**Comment by Lehren** [comment]
And be sure to build the `settings.json` file with it or else no connection can be made.

**Comment by remcohaszing** [comment]
> The built HTML pages do not have correct image references.
>
> For example src=/01353140e1128935f4fce28cdbd29fe8.png
>
> should be src=../01353140e1128935f4fce28cdbd29fe8.png

I agree the second option would be niced, but the first option works as well. Just serve the dist directory as the root.

**Comment by remcohaszing** [comment]
> And be sure to build the settings.json file with it or else no connection can be made.
> I don't think it is currently.

That's unrelated to fixing the build. It would be a code bug. However, this file is included as intended afaik.

**Comment by remcohaszing** [comment]
Paths are now relative.

**Pull request merged**
